name: linux-lcg

on: [push, pull_request]

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v4
        with:
          skip_duplicate_actions: 'same_content_newer'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  build-lcg-ubuntu-2004:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        LCG: ["LCG_101/x86_64-ubuntu2004-gcc9-opt"]
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
      with:
        cvmfs_repositories: 'sft.cern.ch,geant4.cern.ch'
    - uses: aidasoft/run-lcg-view@v1
      with:
        release-platform: ${{ matrix.LCG }}
        run: |
          PREFIX=${PWD}/install
          # install ip6 repo
          git clone https://github.com/eic/ip6.git eic_ip6
          pushd eic_ip6
          cmake -B build -S . -DCMAKE_INSTALL_PREFIX=${PREFIX}
          cmake --build build -- install
          popd
          # install this repo
          cmake -B build -S . -DCMAKE_INSTALL_PREFIX=${PREFIX}
          cmake --build build -- install
          # link ip6 into install
          ln -sf ../ip6/ip6 ${PREFIX}/share/ecce/ip6
          # check geometry
          source ${PREFIX}/setup.sh
          checkGeometry -c ${DETECTOR_PATH}/${DETECTOR}.xml
    - uses: actions/upload-artifact@v3
      with:
        name: build-lcg-ubuntu2004
        path: install/
        if-no-files-found: error
