name: macos-nix

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v2.4.0
     - uses: cachix/install-nix-action@v16
       with:
         nix_path: nixpkgs=channel:nixpkgs-22.05-darwin
         extra_nix_config: |
           access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
     - uses: cachix/cachix-action@v10
       with:
         name: eic
     - run: nix flake check --keep-going --print-build-logs --no-write-lock-file
