name: macos-lcg

on: [push, pull_request]

jobs:
  macos-1015:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        LCG: ["LCG_101/x86_64-mac1015-clang120-opt",
              "LCG_99/x86_64-mac1015-clang120-opt"]
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
      with:
        cvmfs_repositories: 'sft.cern.ch,geant4.cern.ch'
    - uses: aidasoft/run-lcg-view@v1
      with:
        release-platform: ${{ matrix.LCG }}
        run: |
          cmake -B build -S . --trace
          cmake --build build -- install
