name: macos-lcg

on: [push, pull_request]

jobs:
  macos-1015:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        LCG: ["LCG_101/x86_64-mac1015-clang120-opt",
              "LCG_99/x86_64-mac1015-clang120-opt"]
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
      with:
        cvmfs_repositories: 'sft.cern.ch,geant4.cern.ch'
    - uses: aidasoft/run-lcg-view@v1
      with:
        release-platform: ${{ matrix.LCG }}
        run: |
          set -x
          cmake -B build -S .
          VERBOSE=1 cmake --build build -- install || true
          otool -l build/lib/libecce.dylib
          otool -L build/lib/libecce.dylib
          cd build/lib/
          DYLD_LIBRARY_PATH=/Users/runner/work/ecce/ecce/build/lib:/Users/Shared/cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-mac1015-clang120-opt/lib DYLD_PRINT_LIBRARIES=1 DYLD_PRINT_LIBRARIES_POST_LAUNCH=1 listcomponents_dd4hep -o libecce.components libecce.dylib
